### ISSUE TITLE
文档中Download的链接已经失效，没有找到vgg16.weights，能否重新放一个有效的链接

### ISSUE THREAD

**Issue by www6v** [yangboz/visual_search_go#2]
文档中Download的链接已经失效，没有找到vgg16.weights，能否重新放一个有效的链接？谢谢

**Comment by yangboz** [comment]
https://gist.github.com/nitish11/73ba862753929e08b3b319ff1e8c9c09

**Comment by www6v** [comment]
vgg16.py的499行#self._caffe_layers = pickle.load(f) 装载vgg16_weights.h5会报错，确定用的是vgg16_weights .h5文件嘛？ 谢谢
